name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort mypy

    - name: Run flake8
      run: flake8 app tests run.py

    - name: Run black
      run: black --check app tests run.py

    - name: Run isort
      run: isort --profile=black --check-only app run.py

    - name: Run mypy
      run: mypy app

    - name: Run tests
      run: PYTHONPATH=$PWD pytest